program Luncher;


uses
    Vcl.Forms,
    Unity.ChkListBox in 'Extensions\Unity.ChkListBox.pas',
    Unity.Edit in 'Extensions\Unity.Edit.pas',
    Unity.Panel in 'Extensions\Unity.Panel.pas',
    Unity.Shape in 'Extensions\Unity.Shape.pas',
    Unity.Grid in 'Extensions\Unity.Grid.pas',
    Unity.ListView in 'Extensions\Unity.ListView.pas',
    Unity.ComboBox in 'Extensions\Unity.ComboBox.pas',
    Unity.Crc32 in 'Helpers\Unity.Crc32.pas',
    Unity.Enums in 'Helpers\Unity.Enums.pas',
    Unity.Records in 'Helpers\Unity.Records.pas',
    Unity.Constants in 'Helpers\Unity.Constants.pas',
    Unity.Sorting in 'Helpers\Unity.Sorting.pas',
    Unity.Helpers in 'Helpers\Unity.Helpers.pas',
    Unity.Types in 'Helpers\Unity.Types.pas',
    Unity.Mediator in 'Logic\Unity.Mediator.pas',
    Unity.Service in 'Logic\Unity.Service.pas',
    Unity.RestWrapper in 'Logic\Communication\Unity.RestWrapper.pas',
    Unity.Settings in 'Logic\Configuration\Unity.Settings.pas',
    Unity.EventLogger in 'Logic\Logger\Unity.EventLogger.pas',
    Unity.ThreadUtilities in 'Logic\Logger\Unity.ThreadUtilities.pas',
    Layout.AgeViewModel in 'Model\Layout.AgeViewModel.pas',
    Api.DocumentStatusFields in 'Model\Api.DocumentStatusFields.pas',
    Api.DocumentFields in 'Model\Api.DocumentFields.pas',
    Api.ReportListFields in 'Model\Api.ReportListFields.pas',
    Api.UserDailyCommentsFields in 'Model\Api.UserDailyCommentsFields.pas',
    Api.AddressBookFields in 'Model\Api.AddressBookFields.pas',
    Api.UserCompanyFields in 'Model\Api.UserCompanyFields.pas',
    Api.CompaniesFields in 'Model\Api.CompaniesFields.pas',
    Api.ControlStatusFields in 'Model\Api.ControlStatusFields.pas',
    Api.PaidInfoFields in 'Model\Api.PaidInfoFields.pas',
    Api.PaymentTermsFields in 'Model\Api.PaymentTermsFields.pas',
    Api.SalesResponsibleFields in 'Model\Api.SalesResponsibleFields.pas',
    Api.PersonResponsibleFields in 'Model\Api.PersonResponsibleFields.pas',
    Api.AccountTypeFields in 'Model\Api.AccountTypeFields.pas',
    Api.CustomerGroupFields in 'Model\Api.CustomerGroupFields.pas',
    Api.OpenItemsFields in 'Model\Api.OpenItemsFields.pas',
    Api.DetailsFields in 'Model\Api.DetailsFields.pas',
    Api.UserPermissions in 'Model\Api.UserPermissions.pas',
    Api.CustomerSnapshot in 'Model\Api.CustomerSnapshot.pas',
    Api.CustomerSnapshotEx in 'Model\Api.CustomerSnapshotEx.pas',
    Api.FollowUpData in 'Model\Api.FollowUpData.pas',
    Api.FreeFields in 'Model\Api.FreeFields.pas',
    Api.MetaData in 'Model\Api.MetaData.pas',
    Api.ErrorHandler in 'Model\Api.ErrorHandler.pas',
    Api.BankDetails in 'Model\Api.BankDetails.pas',
    Api.StatementData in 'Model\Api.StatementData.pas',
    Api.SendDocument in 'Model\Requests\Api.SendDocument.pas',
    Api.AddressBookAddBulk in 'Model\Requests\Api.AddressBookAddBulk.pas',
    Api.UserSessionAdd in 'Model\Requests\Api.UserSessionAdd.pas',
    Api.UserCompanySelection in 'Model\Requests\Api.UserCompanySelection.pas',
    Api.UserSessionLogs in 'Model\Requests\Api.UserSessionLogs.pas',
    Api.SendEmail in 'Model\Requests\Api.SendEmail.pas',
    Api.UserGeneralCommentAdd in 'Model\Requests\Api.UserGeneralCommentAdd.pas',
    Api.UserGeneralCommentUpdate in 'Model\Requests\Api.UserGeneralCommentUpdate.pas',
    Api.UserDailyCommentAdd in 'Model\Requests\Api.UserDailyCommentAdd.pas',
    Api.UserDailyCommentUpdate in 'Model\Requests\Api.UserDailyCommentUpdate.pas',
    Api.LogSentDocument in 'Model\Requests\Api.LogSentDocument.pas',
    Api.AddressBookAdd in 'Model\Requests\Api.AddressBookAdd.pas',
    Api.AddressBookUpdate in 'Model\Requests\Api.AddressBookUpdate.pas',
    Api.UserCustSnapshotList in 'Model\Requests\Api.UserCustSnapshotList.pas',
    Api.UpdateFreeFields in 'Model\Requests\Api.UpdateFreeFields.pas',
    Api.FollowUpsUpdate in 'Model\Requests\Api.FollowUpsUpdate.pas',
    Api.UserRatingAdd in 'Model\Requests\Api.UserRatingAdd.pas',
    Api.UserRatingUpdate in 'Model\Requests\Api.UserRatingUpdate.pas',
    Api.UserSessionChecked in 'Model\Responses\Api.UserSessionChecked.pas',
    Api.UserCompanyList in 'Model\Responses\Api.UserCompanyList.pas',
    Api.UserSessionAdded in 'Model\Responses\Api.UserSessionAdded.pas',
    Api.UserCompaniesUpdated in 'Model\Responses\Api.UserCompaniesUpdated.pas',
    Api.CustSortingOptions in 'Model\Responses\Api.CustSortingOptions.pas',
    Api.UserSessionLogsSaved in 'Model\Responses\Api.UserSessionLogsSaved.pas',
    Api.SentEmail in 'Model\Responses\Api.SentEmail.pas',
    Api.UserGeneralCommentAdded in 'Model\Responses\Api.UserGeneralCommentAdded.pas',
    Api.UserGeneralCommentUpdated in 'Model\Responses\Api.UserGeneralCommentUpdated.pas',
    Api.UserGeneralComment in 'Model\Responses\Api.UserGeneralComment.pas',
    Api.UserDailyCommentAdded in 'Model\Responses\Api.UserDailyCommentAdded.pas',
    Api.UserDailyCommentUpdated in 'Model\Responses\Api.UserDailyCommentUpdated.pas',
    Api.UserDailyCommentsList in 'Model\Responses\Api.UserDailyCommentsList.pas',
    Api.UserDailyCommentCheck in 'Model\Responses\Api.UserDailyCommentCheck.pas',
    Api.LoggedSentDocument in 'Model\Responses\Api.LoggedSentDocument.pas',
    Api.AddressBookList in 'Model\Responses\Api.AddressBookList.pas',
    Api.AddressBookItem in 'Model\Responses\Api.AddressBookItem.pas',
    Api.AddressBookAdded in 'Model\Responses\Api.AddressBookAdded.pas',
    Api.AddressBookItemDel in 'Model\Responses\Api.AddressBookItemDel.pas',
    Api.UserRating in 'Model\Responses\Api.UserRating.pas',
    Api.UserRatingAdded in 'Model\Responses\Api.UserRatingAdded.pas',
    Api.UserRatingUpdated in 'Model\Responses\Api.UserRatingUpdated.pas',
    Api.ReturnCompanies in 'Model\Responses\Api.ReturnCompanies.pas',
    Api.ReturnAccountType in 'Model\Responses\Api.ReturnAccountType.pas',
    Api.ReturnPaidInfo in 'Model\Responses\Api.ReturnPaidInfo.pas',
    Api.ReturnControlStatus in 'Model\Responses\Api.ReturnControlStatus.pas',
    Api.ReturnPersonResponsible in 'Model\Responses\Api.ReturnPersonResponsible.pas',
    Api.ReturnSalesResponsible in 'Model\Responses\Api.ReturnSalesResponsible.pas',
    Api.ReturnPaymentTerms in 'Model\Responses\Api.ReturnPaymentTerms.pas',
    Api.ReturnCustomerGroup in 'Model\Responses\Api.ReturnCustomerGroup.pas',
    Api.ReturnSsisData in 'Model\Responses\Api.ReturnSsisData.pas',
    Api.ReturnOpenItems in 'Model\Responses\Api.ReturnOpenItems.pas',
    Api.ReturnCustomerSnapshots in 'Model\Responses\Api.ReturnCustomerSnapshots.pas',
    Api.TokenGranted in 'Model\Responses\Api.TokenGranted.pas',
    Api.AddressBookUpdated in 'Model\Responses\Api.AddressBookUpdated.pas',
    Api.UserGeneralCommentCheck in 'Model\Responses\Api.UserGeneralCommentCheck.pas',
    Api.ReturnClientInfo in 'Model\Responses\Api.ReturnClientInfo.pas',
    Api.FreeFieldsUpdated in 'Model\Responses\Api.FreeFieldsUpdated.pas',
    Api.FollowUpsUpdated in 'Model\Responses\Api.FollowUpsUpdated.pas',
    Api.ReturnCustomerReport in 'Model\Responses\Api.ReturnCustomerReport.pas',
    Api.UserPermissionList in 'Model\Responses\Api.UserPermissionList.pas',
    Api.LatestAzureJobStatus in 'Model\Responses\Api.LatestAzureJobStatus.pas',
    Api.ReturnCompanyEmails in 'Model\Responses\Api.ReturnCompanyEmails.pas',
    Api.ReturnReportList in 'Model\Responses\Api.ReturnReportList.pas',
    Api.AddressBookAddedBulk in 'Model\Responses\Api.AddressBookAddedBulk.pas',
    Api.SentDocument in 'Model\Responses\Api.SentDocument.pas',
    Sync.Utility in 'Logic\Business\Sync.Utility.pas',
    Async.Accounts in 'Logic\Business\Async.Accounts.pas',
    Async.Utilities in 'Logic\Business\Async.Utilities.pas',
    Async.AddressBook in 'Logic\Business\Async.AddressBook.pas',
    Async.Debtors in 'Logic\Business\Async.Debtors.pas',
    Async.OpenItems in 'Logic\Business\Async.OpenItems.pas',
    Async.Comments in 'Logic\Business\Async.Comments.pas',
    Async.Documents in 'Logic\Business\Async.Documents.pas',
    Async.Companies in 'Logic\Business\Async.Companies.pas',
    Async.Mailer in 'Logic\Business\Async.Mailer.pas',
    Async.GeneralTables in 'Logic\Business\Async.GeneralTables.pas',
    View.Luncher in 'View\View.Luncher.pas';


{$R *.res}


begin
    Application.Initialize;
    Application.MainFormOnTaskbar:=False;
    LuncherForm.Show();
    Application.Run;
end.
