/// <para>
/// 	Name:             Unity for Debt Management
/// 	Version:          1.0
/// 	(C)(R):           Tomasz Kandula
/// 	Originate:        10-07-2016 (Concept & GUI)
/// 	IDE:              RAD Studio with Delphi XE2 (migrated to Delphi Tokyo)
/// 	Target:           Microsoft Windows 7 or newer
/// 	Dependencies:     Synopse Zip and own libraries
/// 	NET Framework:    Required 4.6 or newer (Lync / Skype calls)
/// 	LYNC version:     2013 or newer
/// </para>
///
/// <remarks>
///     Dependencies:
///         \Projects\Unity Project\__Unity\Using\Adodb
///         \Projects\Unity Project\__Unity\Using\BCrypt
///         \Projects\Unity Project\__Unity\Using\Cdosys
///         \Projects\Unity Project\__Unity\Using\CRC32
///         \Projects\Unity Project\__Unity\Using\Synopse
///         \Projects\Unity Project\__Unity\Using\WinHttp
/// </remarks>
///
/// <para>
///     Prerequisites:
///         \Projects\Unity Project\Components\CEF4Delphi\bin
///         \Projects\Unity Project\Components\CEF4Delphi\sources
///
///     <seealso cref="\Projects\Unity Project\Components\Readme.txt"/>
///
/// </para>
///
/// <para>
///     Structure:
///         \Projects\Unity Project\__Unity\Model
///         \Projects\Unity Project\__Unity\View
///         \Projects\Unity Project\__Unity\Logic
///         \Projects\Unity Project\__Unity\Include
/// </para>
